<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="airlines.aspx.cs" Inherits="AirlineReservation.airlines" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage airlines</title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 373px;
        }
        .auto-style3 {
            width: 373px;
            height: 30px;
        }
        .auto-style4 {
            height: 30px;
        }
    </style>
</head>
<body>
    <h1>MANAGE AIRLINES</h1>
    <form id="form1" runat="server">
        <div>
            Available airlines:<br />
            <asp:GridView ID="GridViewAirlines" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" CellPadding="4" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Seats" HeaderText="Seats" SortExpression="Seats" />
                    <asp:BoundField DataField="AvailableSeats" HeaderText="AvailableSeats" SortExpression="AvailableSeats" />
                    <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                    <asp:BoundField DataField="Source" HeaderText="Source" SortExpression="Source" />
                    <asp:BoundField DataField="STime" HeaderText="STime" SortExpression="STime" />
                    <asp:BoundField DataField="Destination" HeaderText="Destination" SortExpression="Destination" />
                    <asp:BoundField DataField="DTime" HeaderText="DTime" SortExpression="DTime" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="SELECT * FROM [Airline]"
                UpdateCommand= "UPDATE [Airline] SET [Name] = @Name, [Seats] = @Seats, [AvailableSeats]=@AvailableSeats, [Price] = @Price
                , [Source]=@Source, [STime]=@STime, [Destination]=@Destination, [DTime] = @DTime
                WHERE [Id] = @Id"
                DeleteCommand="DELETE FROM [Airline] WHERE [Id]=@Id">
            </asp:SqlDataSource>
            
            <br />
            <br />
            <asp:Panel ID="PanelAddAirlineButton" runat="server">
                <asp:Button ID="btnAddAirline" runat="server" OnClick="btnAddAirline_Click" Text="Add Airline" />
            </asp:Panel>
            <br />
            <asp:Panel ID="PanelManageAirline" runat="server">
                <table class="auto-style1">
                    <tr>
                        <td class="auto-style2">Name</td>
                        <td>
                            <asp:TextBox ID="AirlineName" runat="server" ></asp:TextBox>
                            <asp:RequiredFieldValidator runat="server" ControlToValidate="AirlineName" ErrorMessage="Name is required" ForeColor="Red" ID="RequiredFieldValidator9"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">Seats</td>
                        <td>
                            <asp:TextBox ID="AirlineSeats" runat="server" TextMode="Number"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="AirlineSeats" ErrorMessage="Seats required " ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">Available seats</td>
                        <td>
                            <asp:TextBox ID="AirlineAvailableSeats" runat="server"  TextMode="Number"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="AirlineSeats" ErrorMessage="Available seats required" ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style3">Price</td>
                        <td class="auto-style4">
                            <asp:TextBox ID="AirlinePrice" runat="server" TextMode="Number"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="AirlinePrice" ErrorMessage="Price is required " ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">Source</td>
                        <td>
                            <asp:TextBox ID="AirlineSource" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="AirlineSource" ErrorMessage="Airline Source is required" ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">STime</td>
                        <td>
                            <asp:TextBox ID="AirlineSTime" runat="server" TextMode="DateTime"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ControlToValidate="AirlineSTime" ErrorMessage="Source time is required " ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">Destination</td>
                        <td>
                            <asp:TextBox ID="AirlineDestination" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" ControlToValidate="AirlineDestination" ErrorMessage="Destination is required " ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td id="AirlineDTime0" aria-dropeffect="none" class="auto-style2">DTime</td>
                        <td>
                            <asp:TextBox ID="AirlineDTime" runat="server" TextMode="DateTime"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator8" runat="server" ControlToValidate="AirlineDTime" ErrorMessage="Destination time is required" ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td id="AirlineDTime0" aria-dropeffect="none" class="auto-style2">
                            <asp:Button ID="ButtonAddAirlineSubmit" runat="server" OnClick="ButtonSubmit_Click" Text="Submit" />
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </asp:Panel>
            <br />
        </div>
    </form>
    <asp:HyperLink runat="server" ID="hlHome" ForeColor="Blue" NavigateUrl="~/adminhome.aspx">Back to homepage</asp:HyperLink>
</body>
</html>
